#!/usr/bin/env python
# coding=utf-8

'''
Case Description
Case Name:
    非管理用户登录验证
Pre-Condition:
    已有普通用户(非管理账号)账号
Test Steps:
    1. 打开登录页面
    2. 输入非管理账号密码
    3. 点击登录按钮
Expected Results:
    1. 登录成功
    2. 页面切换至账号信息界面
End Description
'''

from login_logout import *
import argparse


class LoginLogoutCommon(LoginLogout):
    def setUp(self):
        super(LoginLogoutCommon, self).setUp()
        self.user_type = 'common'


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Log in with commone account.')
    parser.add_argument('log_path', nargs='?', default='.', help='Log path.')

    args = parser.parse_args()

    # Log.
    log_path = args.log_path
    if not os.path.exists(log_path):
        os.makedirs(log_path)
    log_fn = os.path.join(log_path, '%s.log' % os.path.basename(__file__))
    config_path = os.path.join(os.environ['AI_AUTO_ROOT'], 'configs')
    conf_fn = os.path.abspath(os.path.join(config_path, "logging.json"))
    conf_data = json.load(open(conf_fn, 'r'))
    conf_data['handlers']['file_handler']['filename'] = log_fn
    logging.config.dictConfig(conf_data)
    logger = logging.getLogger()

    # Run test case.
    suite = unittest.TestSuite()
    suite.addTest(LoginLogoutCommon("test_login"))
    runner = unittest.TextTestRunner()
    runner.run(suite)
