#!/usr/bin/env python
# coding=utf-8

from login_logout import *
import argparse


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Log in with admin account.')
    parser.add_argument('log_path', nargs='?', default='.', help='Log path.')

    args = parser.parse_args()

    # Log.
    log_path = args.log_path
    if not os.path.exists(log_path):
        os.makedirs(log_path)
    log_fn = os.path.join(log_path, '%s.log' % os.path.basename(__file__))
    conf_fn = os.path.abspath(os.path.join(os.environ['AI_AUTO_ROOT'], 'configs', "logging.json"))
    conf_data = json.load(open(conf_fn, 'r'))
    conf_data['handlers']['file_handler']['filename'] = log_fn
    logging.config.dictConfig(conf_data)
    logger = logging.getLogger()

    # Run test case.
    suite = unittest.TestSuite()
    suite.addTest(LoginLogout("test_login"))
    runner = unittest.TextTestRunner()
    runner.run(suite)
